version: "3.8"

services:
  nginx:
    image: "nginx:latest"
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - ${WEB_PORT_HTTP}:80
      - ${WEB_PORT_HTTPS}:443
    depends_on:
      - web
      - mysql
    links:
      - web
    networks:
      - repostator
    volumes:
      - ./src:/var/www/html
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/runtime/logs/nginx:/var/log/nginx
  mysql:
    image: "mysql:5.7"
    restart: always
    container_name: ${PROJECT_NAME}-mysql
    ports:
      - ${DB_PORT}:3306
    networks:
      - repostator
    volumes:
      - ./docker/config/mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/runtime/db/mysql:/var/lib/mysql
      - ./docker/runtime/logs/mysql:/var/log/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_HOST: "%"
  web: &application-template
    container_name: ${PROJECT_NAME}-web
    restart: always
    build:
      context: .
      dockerfile: docker/build/php/Dockerfile
      target: base
      args:
        HOST_UID: 1000
        HOST_GID: 1000
        WEB_PORT_HTTP: ${WEB_PORT_HTTP}
        WEB_PORT_HTTPS: ${WEB_PORT_HTTPS}
    volumes:
      - ./src:/var/www/html
      - ./docker/runtime/composer:/var/www/.composer
    networks:
      - repostator
    links:
      - mysql
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/html
    env_file:
      - .env
    environment:
      PHP_IDE_CONFIG: "serverName=RepostatorServer"
  supervisor:
    <<: *application-template
    container_name: ${PROJECT_NAME}-supervisor
    volumes:
      - ./src:/var/www/html
      - ./docker/config/supervisord.conf:/etc/supervisor/supervisord.conf
    entrypoint: [ "/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf" ]
    environment:
      PHP_IDE_CONFIG: "serverName=RepostatorServer"
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${PROJECT_NAME}-mailhog
    restart: on-failure
    ports:
      - ${MAIL_PORT}:1025
      - 8025:8025
    networks:
      - repostator
networks:
  repostator:
    driver: bridge