version: "3.8"

services:
  nginx:
    image: "nginx:latest"
    container_name: ${PROJECT_NAME}-nginx
    restart: always
    ports:
      - ${WEB_PORT_HTTP}:80
      - ${WEB_PORT_HTTP_TEST}:88
      - ${WEB_PORT_HTTPS}:443
    depends_on:
      - web
      - mysql
    links:
      - web
    volumes:
      - ./src:/var/www/html
      - ./docker/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./docker/runtime/logs/nginx:/var/log/nginx
    networks:
      - repostator
  mysql:
    image: "mysql:5.7"
    restart: always
    container_name: ${PROJECT_NAME}-mysql
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./docker/config/mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/runtime/db:/var/lib/mysql
      - ./docker/runtime/logs/mysql:/var/log
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - repostator
  mysqltest:
    image: "mysql:5.7"
    restart: always
    container_name: ${PROJECT_NAME}-mysqltest
    ports:
      - ${TESTDB_PORT}:${TESTDB_PORT}
    volumes:
      - ./docker/config/mysql-custom.cnf:/etc/mysql/conf.d/custom.cnf
      - ./docker/runtime/db_test:/var/lib/mysql
      - ./docker/runtime/logs/mysql_test:/var/log
    environment:
      MYSQL_TCP_PORT: ${TESTDB_PORT}
      MYSQL_DATABASE: ${TESTDB_NAME}
      MYSQL_ROOT_PASSWORD: ${TESTDB_PASS}
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    networks:
      - repostator
  web: &application-template
    image: "${PROJECT_NAME}-web:latest"
    container_name: ${PROJECT_NAME}-web
    restart: always
    build:
      context: .
      dockerfile: docker/build/php/Dockerfile
      target: base
      args:
        HOST_UID: 1000
        HOST_GID: 1000
        WEB_PORT_HTTP: ${WEB_PORT_HTTP}
        WEB_PORT_HTTPS: ${WEB_PORT_HTTPS}
    volumes:
      - ./src:/var/www/html
      - ./docker/runtime/composer:/var/www/.composer
    links:
      - mysql
    depends_on:
      - mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /var/www/html
    environment:
      PHP_IDE_CONFIG: "serverName=RepostatorServer"
    env_file:
      - .env
    networks:
      - repostator
  supervisor:
    <<: *application-template
    container_name: ${PROJECT_NAME}-supervisor
    volumes:
      - ./src:/var/www/html
      - ./docker/config/supervisord.conf:/etc/supervisor/supervisord.conf
    entrypoint: [ "/usr/bin/supervisord", "-c", "/etc/supervisor/supervisord.conf" ]
    environment:
      PHP_IDE_CONFIG: "serverName=RepostatorServer"
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${PROJECT_NAME}-mailhog
    restart: on-failure
    ports:
      - ${MAIL_PORT}:1025
      - 8025:8025
    networks:
      - repostator
  selenium:
    image: selenium/standalone-firefox:latest
    hostname: selenium,
    ports:
      - '4444:4444'
      - '5900:5900'
    shm_size: 1g
    privileged: true
    volumes:
      - ./src:/var/www/html
    networks:
      - repostator
networks:
  repostator:
    driver: bridge