<?php

return [
    [
        'id' => 1,
        'report_id' => 1,
        'report_datetime' => time(),
        'group_id' => 2,
        'struct_id' => 1,
        'content' => '{"record1":"1"}',
        'created_at' => time(),
        'created_uid' => 1,
        'created_gid' => 1,
    ],
    [
        'id' => 2,
        'report_id' => 1,
        'report_datetime' => time(),
        'group_id' => 2,
        'struct_id' => 1,
        'content' => '{"record2":"1"}',
        'created_at' => time(),
        'created_uid' => 1,
        'created_gid' => 1,
    ],
    [
        'id' => 3,
        'report_id' => 1,
        'report_datetime' => time(),
        'group_id' => 2,
        'struct_id' => 1,
        'content' => '{"record3":"1"}',
        'created_at' => time(),
        'created_uid' => 1,
        'created_gid' => 1,
    ],
    [
        'id' => 4,
        'report_id' => 2,
        'report_datetime' => strtotime(date('Y-m-d')),
        'group_id' => 2,
        'struct_id' => 2,
        'content' => '{"record1":"1","record2":"22","record3":"3","record4":"4","record5":"5"}',
        'created_at' => time(),
        'created_uid' => 1,
        'created_gid' => 1,
        'update_uid' => 1,
    ],
];