<?php

use yii\db\Migration;

final class m240412_140304_rights_itemDataInsert extends Migration
{
    const TABLE = '{{%rights_item}}';

    public function safeUp(): void
    {
        $this->batchInsert(self::TABLE, ["name", "type", "description", "rule_name", "data", "created_at", "created_uid", "updated_at", "updated_uid"], [
            [
                'name' => 'admin',
                'type' => '1',
                'description' => 'Администратор',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.group',
                'type' => '2',
                'description' => 'Управление группами',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.groupType',
                'type' => '2',
                'description' => 'Управление типами групп',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.includes',
                'type' => '2',
                'description' => 'Раздел с административными настройками',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.log',
                'type' => '2',
                'description' => 'Просмотр логов',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.queue',
                'type' => '2',
                'description' => 'Просмотр очередей',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.queue.system',
                'type' => '2',
                'description' => 'Просмотр очередей. Системная',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.queue.template.list',
                'type' => '2',
                'description' => 'Просмотр очередей. Формирование шаблонов',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.queue.template.list.all',
                'type' => '2',
                'description' => 'Просмотр очередей. Формирование шаблонов. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.queue.template.list.group',
                'type' => '2',
                'description' => 'Просмотр очередей. Формирование шаблонов. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.setting',
                'type' => '2',
                'description' => 'Управление настройками',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.create',
                'type' => '2',
                'description' => 'Пользователи. Добавление',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.delete.all',
                'type' => '2',
                'description' => 'Пользователи. Удаление. Своя и подчиненные группы',
                'rule_name' => 'checkUserAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.delete.group',
                'type' => '2',
                'description' => 'Пользователи. Удаление. Своя группа',
                'rule_name' => 'checkUserGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.edit.all',
                'type' => '2',
                'description' => 'Пользователи. Редактирование. Своя и подчиненные группы',
                'rule_name' => 'checkUserAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.edit.group',
                'type' => '2',
                'description' => 'Пользователи. Редактирование. Своя группа',
                'rule_name' => 'checkUserGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.enable.all',
                'type' => '2',
                'description' => 'Пользователи. Восстановление. Своя и подчиненные группы',
                'rule_name' => 'checkUserDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.enable.group',
                'type' => '2',
                'description' => 'Пользователи. Восстановление. Своя группа',
                'rule_name' => 'checkUserDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.list',
                'type' => '2',
                'description' => 'Пользователи. Список',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.list.all',
                'type' => '2',
                'description' => 'Пользователи. Список. Своя и подчиненные группы',
                'rule_name' => 'checkUserAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.list.group',
                'type' => '2',
                'description' => 'Пользователи. Список. Своя группа',
                'rule_name' => 'checkUserGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.view.all',
                'type' => '2',
                'description' => 'Пользователи. Просмотр. Своя и подчиненные группы',
                'rule_name' => 'checkUserAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.view.delete.all',
                'type' => '2',
                'description' => 'Пользователи. Удаленные. Просмотр. Своя и подчиненные группы',
                'rule_name' => 'checkUserDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.view.delete.group',
                'type' => '2',
                'description' => 'Пользователи. Удаленные. Просмотр. Своя группа',
                'rule_name' => 'checkUserDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'admin.user.view.group',
                'type' => '2',
                'description' => 'Пользователи. Просмотр. Своя группа',
                'rule_name' => 'checkUserGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.create',
                'type' => '2',
                'description' => 'Константы. Добавление',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.delete.all',
                'type' => '2',
                'description' => 'Константы. Удаление. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.delete.group',
                'type' => '2',
                'description' => 'Константы. Удаление. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.delete.main',
                'type' => '2',
                'description' => 'Константы. Удаление. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.edit.all',
                'type' => '2',
                'description' => 'Константы. Редактирование. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.edit.group',
                'type' => '2',
                'description' => 'Константы. Редактирование. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.edit.main',
                'type' => '2',
                'description' => 'Константы. Редактирование. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.enable.all',
                'type' => '2',
                'description' => 'Константы. Восстановление. Своя и подчиненные группы',
                'rule_name' => 'checkDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.enable.group',
                'type' => '2',
                'description' => 'Константы. Восстановление. Своя группа',
                'rule_name' => 'checkDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.enable.main',
                'type' => '2',
                'description' => 'Константы. Восстановление. Только свои',
                'rule_name' => 'checkDeleteMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.list',
                'type' => '2',
                'description' => 'Константы. Список',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.list.all',
                'type' => '2',
                'description' => 'Константы. Список. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.list.group',
                'type' => '2',
                'description' => 'Константы. Список. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.list.main',
                'type' => '2',
                'description' => 'Константы. Список. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.view.all',
                'type' => '2',
                'description' => 'Константы. Просмотр. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.view.delete.all',
                'type' => '2',
                'description' => 'Константы. Удаленные. Просмотр. Своя и подчиненные группы',
                'rule_name' => 'checkDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.view.delete.group',
                'type' => '2',
                'description' => 'Константы. Удаленные. Просмотр. Своя группа',
                'rule_name' => 'checkDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.view.delete.main',
                'type' => '2',
                'description' => 'Константы. Удаленные. Просмотр. Только свои',
                'rule_name' => 'checkDeleteMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.view.group',
                'type' => '2',
                'description' => 'Константы. Просмотр. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constant.view.main',
                'type' => '2',
                'description' => 'Константы. Просмотр. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.create',
                'type' => '2',
                'description' => 'Правила сложения. Добавление',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.delete.all',
                'type' => '2',
                'description' => 'Правила сложения. Удаление. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.delete.group',
                'type' => '2',
                'description' => 'Правила сложения. Удаление. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.delete.main',
                'type' => '2',
                'description' => 'Правила сложения. Удаление. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.edit.all',
                'type' => '2',
                'description' => 'Правила сложения. Редактирование. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.edit.group',
                'type' => '2',
                'description' => 'Правила сложения. Редактирование. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.edit.main',
                'type' => '2',
                'description' => 'Правила сложения. Редактирование. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.enable.all',
                'type' => '2',
                'description' => 'Правила сложения. Восстановление. Своя и подчиненные группы',
                'rule_name' => 'checkDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.enable.group',
                'type' => '2',
                'description' => 'Правила сложения. Восстановление. Своя группа',
                'rule_name' => 'checkDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.enable.main',
                'type' => '2',
                'description' => 'Правила сложения. Восстановление. Только свои',
                'rule_name' => 'checkDeleteMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.list',
                'type' => '2',
                'description' => 'Правила сложения. Список',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.list.all',
                'type' => '2',
                'description' => 'Правила сложения. Список. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.list.group',
                'type' => '2',
                'description' => 'Правила сложения. Список. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.list.main',
                'type' => '2',
                'description' => 'Правила сложения. Список. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.view.all',
                'type' => '2',
                'description' => 'Правила сложения. Просмотр. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.view.delete.all',
                'type' => '2',
                'description' => 'Правила сложения. Удаленные. Просмотр. Созданные пользователями своей и подчиненных групп',
                'rule_name' => 'checkDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.view.delete.group',
                'type' => '2',
                'description' => 'Правила сложения. Удаленные. Просмотр. Своя группа',
                'rule_name' => 'checkDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.view.delete.main',
                'type' => '2',
                'description' => 'Правила сложения. Удаленные. Просмотр. Только свои',
                'rule_name' => 'checkDeleteMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.view.group',
                'type' => '2',
                'description' => 'Правила сложения. Просмотр. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'constantRule.view.main',
                'type' => '2',
                'description' => 'Правила сложения. Просмотр. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.change.all',
                'type' => '2',
                'description' => 'Сведения. Просмотр изменений. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.change.group',
                'type' => '2',
                'description' => 'Сведения. Просмотр изменений. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.change.main',
                'type' => '2',
                'description' => 'Сведения. Просмотр изменений. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.checkFull',
                'type' => '2',
                'description' => 'Сведения. Просмотр полноты передачи',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.createFor',
                'type' => '2',
                'description' => 'Сведения. Добавление за подчиненную группу',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.delete.all',
                'type' => '2',
                'description' => 'Сведения. Удаление. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.delete.group',
                'type' => '2',
                'description' => 'Сведения. Удаление. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.delete.main',
                'type' => '2',
                'description' => 'Сведения. Удаление. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.edit.all',
                'type' => '2',
                'description' => 'Сведения. Редактирование. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.edit.group',
                'type' => '2',
                'description' => 'Сведения. Редактирование. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.edit.main',
                'type' => '2',
                'description' => 'Сведения. Редактирование. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.enable.all',
                'type' => '2',
                'description' => 'Сведения. Восстановление. Своя и подчиненные группы',
                'rule_name' => 'checkDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.enable.group',
                'type' => '2',
                'description' => 'Сведения. Восстановление. Своя группа',
                'rule_name' => 'checkDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.enable.main',
                'type' => '2',
                'description' => 'Сведения. Восстановление. Только свои',
                'rule_name' => 'checkDeleteMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.list',
                'type' => '2',
                'description' => 'Сведения. Список',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.list.all',
                'type' => '2',
                'description' => 'Сведения. Список. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.list.group',
                'type' => '2',
                'description' => 'Сведения. Список. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.list.main',
                'type' => '2',
                'description' => 'Сведения. Список. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.send',
                'type' => '2',
                'description' => 'Сведения. Передача',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.send.all',
                'type' => '2',
                'description' => 'Передача сведений за подчиненные группы',
                'rule_name' => 'checkDataAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.view.all',
                'type' => '2',
                'description' => 'Сведения. Просмотр. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.view.delete.all',
                'type' => '2',
                'description' => 'Сведения. Удаленные. Просмотр. Своя и подчиненные группы',
                'rule_name' => 'checkDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.view.delete.group',
                'type' => '2',
                'description' => 'Сведения. Удаленные. Просмотр. Своя группа',
                'rule_name' => 'checkDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.view.delete.main',
                'type' => '2',
                'description' => 'Сведения. Удаленные. Просмотр. Только свои',
                'rule_name' => 'checkDeleteMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.view.group',
                'type' => '2',
                'description' => 'Сведения. Просмотр. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'data.view.main',
                'type' => '2',
                'description' => 'Сведения. Просмотр. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.create',
                'type' => '2',
                'description' => 'Отчеты. Добавление',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.delete.all',
                'type' => '2',
                'description' => 'Отчеты. Удаление. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.delete.group',
                'type' => '2',
                'description' => 'Отчеты. Удаление. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.delete.main',
                'type' => '2',
                'description' => 'Отчеты. Удаление. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.edit.all',
                'type' => '2',
                'description' => 'Отчеты. Редактирование. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.edit.group',
                'type' => '2',
                'description' => 'Отчеты. Редактирование. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.edit.main',
                'type' => '2',
                'description' => 'Отчеты. Редактирование. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.enable.all',
                'type' => '2',
                'description' => 'Отчеты. Восстановление. Своя и подчиненные группы',
                'rule_name' => 'checkDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.enable.group',
                'type' => '2',
                'description' => 'Отчеты. Восстановление. Своя группа',
                'rule_name' => 'checkDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.enable.main',
                'type' => '2',
                'description' => 'Отчеты. Восстановление. Только свои',
                'rule_name' => 'checkDeleteMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.includes',
                'type' => '2',
                'description' => 'Раздел с настройкой компонентов отчетов',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.list',
                'type' => '2',
                'description' => 'Отчеты. Список',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.list.all',
                'type' => '2',
                'description' => 'Отчеты. Список. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.list.group',
                'type' => '2',
                'description' => 'Отчеты. Список. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.view.all',
                'type' => '2',
                'description' => 'Отчеты. Просмотр. Своя и починенные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.view.delete.all',
                'type' => '2',
                'description' => 'Отчеты. Удаленные. Просмотр. Своя и подчиненные группы',
                'rule_name' => 'checkDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.view.delete.group',
                'type' => '2',
                'description' => 'Отчеты. Удаленные. Просмотр. Своя группа',
                'rule_name' => 'checkDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.view.delete.main',
                'type' => '2',
                'description' => 'Отчеты. Удаленные. Просмотр. Только свои',
                'rule_name' => 'checkDeleteMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.view.group',
                'type' => '2',
                'description' => 'Отчеты. Просмотр. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'report.view.main',
                'type' => '2',
                'description' => 'Отчеты. Просмотр. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_adminGroup',
                'type' => '1',
                'description' => 'Админка. Группы. Управление',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_adminGroupType',
                'type' => '1',
                'description' => 'Админка. Типы групп. Управление',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_adminLog',
                'type' => '1',
                'description' => 'Админка. Логи',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_adminQueueSystem',
                'type' => '1',
                'description' => 'Админка. Очереди. Системная',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_adminQueueTemplateAll',
                'type' => '1',
                'description' => 'Админка. Очереди. Шаблоны. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_adminQueueTemplateGroup',
                'type' => '1',
                'description' => 'Админка. Очереди. Шаблоны. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_adminUserAdd',
                'type' => '1',
                'description' => 'Админка. Пользователи. Создание',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_adminUserAll',
                'type' => '1',
                'description' => 'Админка. Пользователи. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_adminUserDeletedAll',
                'type' => '1',
                'description' => 'Админка. Пользователи. Удаленные. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_adminUserDeletedGroup',
                'type' => '1',
                'description' => 'Админка. Пользователи. Удаленные. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_adminUserGroup',
                'type' => '1',
                'description' => 'Админка. Пользователи. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantAdd',
                'type' => '1',
                'description' => 'Константы. Создание',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantAll',
                'type' => '1',
                'description' => 'Константы. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantDeletedAll',
                'type' => '1',
                'description' => 'Константы. Удаленные. Своия и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantDeletedGroup',
                'type' => '1',
                'description' => 'Константы. Удаленные. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantDeletedMain',
                'type' => '1',
                'description' => 'Константы. Удаленные. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantGroup',
                'type' => '1',
                'description' => 'Константы. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantMain',
                'type' => '1',
                'description' => 'Константы. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantRuleAdd',
                'type' => '1',
                'description' => 'Правила сложения. Создание',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantRuleAll',
                'type' => '1',
                'description' => 'Правила сложения. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantRuleDeletedAll',
                'type' => '1',
                'description' => 'Правила сложения. Удаленные. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantRuleDeletedGroup',
                'type' => '1',
                'description' => 'Правила сложения. Удаленные. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantRuleDeletedMain',
                'type' => '1',
                'description' => 'Правила сложения. Удаленные. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantRuleGroup',
                'type' => '1',
                'description' => 'Правила сложения. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_constantRuleMain',
                'type' => '1',
                'description' => 'Правила сложения. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_dataAll',
                'type' => '1',
                'description' => 'Сведения. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_dataDeletedAll',
                'type' => '1',
                'description' => 'Сведения. Удаленные. Своя и подчиенные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_dataDeletedGroup',
                'type' => '1',
                'description' => 'Сведения. Удаленные. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_dataDeletedMain',
                'type' => '1',
                'description' => 'Сведения. Удаленные. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_dataGroup',
                'type' => '1',
                'description' => 'Сведения. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_dataMain',
                'type' => '1',
                'description' => 'Сведения. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_report',
                'type' => '',
                'description' => null,
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_reportAdd',
                'type' => '1',
                'description' => 'Отчеты. Создание',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_reportAll',
                'type' => '1',
                'description' => 'Отчеты. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_reportDeletedAll',
                'type' => '1',
                'description' => 'Отчеты. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_reportDeletedGroup',
                'type' => '1',
                'description' => 'Отчеты. Удаленные. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_reportDeleteMain',
                'type' => '1',
                'description' => 'Отчеты. Удаленные. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_reportGroup',
                'type' => '1',
                'description' => 'Отчеты. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_reportMain',
                'type' => '1',
                'description' => 'Отчеты. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_structureAdd',
                'type' => '1',
                'description' => 'Структуры. Создание',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_structureAll',
                'type' => '1',
                'description' => 'Структуры. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_structureDeletedAll',
                'type' => '1',
                'description' => 'Структуры. Удаленные. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_structureDeletedGroup',
                'type' => '1',
                'description' => 'Структуры. Удаленные. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_structureDeletedMain',
                'type' => '1',
                'description' => 'Структуры. Удаленные. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_structureGroup',
                'type' => '1',
                'description' => 'Структуры. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_structureMain',
                'type' => '1',
                'description' => 'Структуры. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_tempalteAdd',
                'type' => '1',
                'description' => 'Шаблоны. Создание',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_tempateGroup',
                'type' => '1',
                'description' => 'Шаблоны. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_templateAll',
                'type' => '1',
                'description' => 'Шаблоны. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_templateDeletedAll',
                'type' => '1',
                'description' => 'Шаблоны. Удаленные. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_templateDeletedGroup',
                'type' => '1',
                'description' => 'Шаблоны. Удаленные. Своя группа',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_templateDeletedMain',
                'type' => '1',
                'description' => 'Шаблоны. Удаленные. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_templateMain',
                'type' => '1',
                'description' => 'Шаблоны. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'statistic',
                'type' => '2',
                'description' => 'Формирование отчетов',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.create',
                'type' => '2',
                'description' => 'Структуры передачи. Добавление',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.delete.all',
                'type' => '2',
                'description' => 'Структуры передачи. Удаление. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.delete.group',
                'type' => '2',
                'description' => 'Структуры передачи. Удаление. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.delete.main',
                'type' => '2',
                'description' => 'Структуры передачи. Удаление. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.edit.all',
                'type' => '2',
                'description' => 'Структуры передачи. Редактирование. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.edit.group',
                'type' => '2',
                'description' => 'Структуры передачи. Редактирование. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.edit.main',
                'type' => '2',
                'description' => 'Структуры передачи. Редактирование. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.enable.all',
                'type' => '2',
                'description' => 'Структуры передачи. Восстановление. Своя и подчиненные группы',
                'rule_name' => 'checkDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.enable.group',
                'type' => '2',
                'description' => 'Структуры передачи. Восстановление. Своя группа',
                'rule_name' => 'checkDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.enable.main',
                'type' => '2',
                'description' => 'Структуры передачи. Восстановление. Только свои',
                'rule_name' => 'checkDeleteMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.list',
                'type' => '2',
                'description' => 'Структуры передачи. Список',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.list.all',
                'type' => '2',
                'description' => 'Структуры передачи. Список. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.list.group',
                'type' => '2',
                'description' => 'Структуры передачи. Список. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.list.main',
                'type' => '2',
                'description' => 'Структуры передачи. Список. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.view.all',
                'type' => '2',
                'description' => 'Структуры передачи. Просмотр. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.view.delete.all',
                'type' => '2',
                'description' => 'Структуры передачи. Удаленные. Просмотр. Своя и подчиненные группы',
                'rule_name' => 'checkDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.view.delete.group',
                'type' => '2',
                'description' => 'Структуры передачи. Удаленные. Просмотр. Своя группа',
                'rule_name' => 'checkDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.view.delete.main',
                'type' => '2',
                'description' => 'Структуры передачи. Удаленные. Просмотр. Только свои',
                'rule_name' => 'checkDeleteMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.view.group',
                'type' => '2',
                'description' => 'Структуры передачи. Просмотр. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'structure.view.main',
                'type' => '2',
                'description' => 'Структуры передачи. Просмотр. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.create',
                'type' => '2',
                'description' => 'Шаблоны формирования. Добавление',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.delete.all',
                'type' => '2',
                'description' => 'Шаблоны формирования. Удаление. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.delete.group',
                'type' => '2',
                'description' => 'Шаблоны формирования. Удаление. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.delete.main',
                'type' => '2',
                'description' => 'Шаблоны формирования. Удаление. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.edit.all',
                'type' => '2',
                'description' => 'Шаблоны формирования. Редактирование. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.edit.group',
                'type' => '2',
                'description' => 'Шаблоны формирования. Редактирование. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.edit.main',
                'type' => '2',
                'description' => 'Шаблоны формирования. Редактирование. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.enable.all',
                'type' => '2',
                'description' => 'Шаблоны формирования. Восстановление. Своя и подчиненные группы',
                'rule_name' => 'checkDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.enable.group',
                'type' => '2',
                'description' => 'Шаблоны формирования. Восстановление. Своя группа',
                'rule_name' => 'checkDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.enable.main',
                'type' => '2',
                'description' => 'Шаблоны формирования. Восстановление. Только свои',
                'rule_name' => 'checkDeleteMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.list',
                'type' => '2',
                'description' => 'Шаблоны формирования. Список',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.list.all',
                'type' => '2',
                'description' => 'Шаблоны формирования. Список. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.list.group',
                'type' => '2',
                'description' => 'Шаблоны формирования. Список. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.list.main',
                'type' => '2',
                'description' => 'Шаблоны формирования. Список. Только свои',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.view.all',
                'type' => '2',
                'description' => 'Шаблоны формирования. Просмотр. Своя и подчиненные группы',
                'rule_name' => 'checkAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.view.delete.all',
                'type' => '2',
                'description' => 'Шаблоны формирования. Удаленные. Просмотр. Своя и подчиненные группы',
                'rule_name' => 'checkDeleteAll',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.view.delete.group',
                'type' => '2',
                'description' => 'Шаблоны формирования. Удаленные. Просмотр. Своя группа',
                'rule_name' => 'checkDeleteGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.view.delete.main',
                'type' => '2',
                'description' => 'Шаблоны формирования. Удаленные. Просмотр. Только свои',
                'rule_name' => 'checkDeleteMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.view.group',
                'type' => '2',
                'description' => 'Шаблоны формирования. Просмотр. Своя группа',
                'rule_name' => 'checkGroup',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'template.view.main',
                'type' => '2',
                'description' => 'Шаблоны формирования. Просмотр. Только свои',
                'rule_name' => 'checkMain',
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_dataCreateFor',
                'type' => '1',
                'description' => 'Сведения. Передача за группу. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
            [
                'name' => 'role_dataCheckFull',
                'type' => '1',
                'description' => 'Сведения. Проверка полноты передачи. Своя и подчиненные группы',
                'rule_name' => null,
                'data' => null,
                'created_at' => 1712688916,
                'created_uid' => 1,
                'updated_at' => null,
                'updated_uid' => null,
            ],
        ]);
    }

    public function safeDown(): void
    {
        $this->truncateTable(self::TABLE . ' CASCADE');
    }
}
