#!/usr/bin/env php
<?php

defined('YII_DEBUG') or define('YII_DEBUG', (bool)getenv('YII_DEBUG', true));
defined('YII_ENV') or define('YII_ENV', (bool)getenv('YII_ENV', 'dev'));

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

use yii\{
    base\InvalidConfigException,
    console\Application,
};

$config = require __DIR__ . '/application/config/console.php';

try {
    exit((new Application($config))->run());
} catch (InvalidConfigException $e) {echo $e->getMessage();}
