#!/usr/bin/env php
<?php

/**
 * Yii console bootstrap file.
 */

require __DIR__ . '/vendor/autoload.php';

define('YII_DEBUG', getenv('YII_DEBUG', true));
define('YII_ENV', getenv('YII_ENV', 'test'));

require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';
require __DIR__ . '/application/config/bootstrap.php';

use yii\{
    base\InvalidConfigException,
    console\Application,
};

$config = require __DIR__ . '/application/config/console.php';

try {
    $application = new Application($config);
    $exitCode = $application->run();
    exit($exitCode);
} catch (InvalidConfigException $e) {}