#!/usr/bin/env php
<?php

/**
 * Yii console bootstrap file.
 *
 * @link https://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license https://www.yiiframework.com/license/
 */

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

defined('YII_DEBUG') or define('YII_DEBUG', getenv('YII_DEBUG'));
defined('YII_ENV') or define('YII_ENV', getenv('YII_ENV'));

use yii\{
    base\Exception,
    console\Application,
};

$config = require __DIR__ . '/application/config/console.php';

try {
    exit((new Application($config))->run());
} catch (Exception $e) {
    echo $e->getMessage();
}