#!/usr/bin/env php
<?php

define('YII_DEBUG', true);
define('YII_ENV', 'test');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

use yii\{
    base\InvalidConfigException,
    console\Application,
    helpers\ArrayHelper
};

$config = ArrayHelper::merge(
    require __DIR__ . '/application/config/console.php',
    require __DIR__ . '/application/config/test.php'

try {
    exit((new Application($config))->run());
} catch (InvalidConfigException $e) {
    echo $e->getMessage();
}
